### PR TITLE
1.0.8

### LINKED ISSUE #14: %sid%/results?count=0 ,
Using curl and i query my saved report, if i add /results?count=0 on the end of my sid it returns all data in the report. If you dont set this it only returns about 1000

By using get-splunksearchjobsresults is there a way i can get the whole report?
It seems to just grab 100 , im expecting about 40K

Any ideas how i can get more than 100 lines?
``
, if a place /results?count=0 at the end of my sid
 it throws this error

 `:`Invoke-WebRequest : 
  
    Invalid count.
  
At C:\Program Files\WindowsPowerShell\Modules\UMN-SplunkRA-master\UMN-SplunkRA.psm1:155 char:23
+ ... se{$data = (Invoke-WebRequest -Uri $uri -Headers $header -UseBasicPar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Csv : Cannot validate argument on parameter 'InputObject'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At C:\Program Files\WindowsPowerShell\Modules\UMN-SplunkRA-master\UMN-SplunkRA.psm1:156 char:53
+         if ($outPutmode -eq 'csv'){ return ($data | ConvertFrom-Csv)}
+                                                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ConvertFromCsvCommand``

### PR DESCRIPTION
**Pull request by travis-sobeck**
Add resultSize param to Get-SplunkSearchJobsResults and Invoke-SplunkBase to allow for getting more or less than the default 100 results.
fix for https://github.com/umn-microsoft-automation/UMN-SplunkRA/issues/14

### CODE REVIEW

**Review by FISHMANPET — CHANGES_REQUESTED** [review]
Forgot to bump the version in the psd1 file, once that's fixed, looks good

**Review by FISHMANPET — APPROVED** [review]
Nevermind, the PSD1 is changed, it's just in binary

**Comment by vandelin586** [comment]
Thank you for all this work and the results thing works.
however since the newest version it is cutting off the last two header which is the time and date.
My saved report had four headings. I'm not sure but I believe powershell might be truncating those extra fields for some reason. In my console window the last two headings are missing as well when i write it out to a file.

Is there anything we can do about this?
I can open another issue

**Comment by travis-sobeck** [comment]
@vandelin586 yeah, go ahead and open a separate issue,thanks.

**Pull request merged**
